# -*- coding: utf-8 -*-
"""1-Regresión Lineal.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UEx-z7sfh3-stbfdLaNRUp5G2PaQ7eC-

# Regresión lineal del precio de la vivienda en EE. UU.

## Primer de regresión lineal

En estadística, la regresión lineal es un enfoque lineal para modelar la relación entre una variable dependiente escalar y y una o más variables explicativas (o variables independientes) denominadas X. El caso de una variable explicativa se denomina regresión lineal simple. Para más de una variable explicativa, el proceso se denomina regresión lineal múltiple.

Los modelos de regresión lineal a menudo se ajustan utilizando el enfoque de mínimos cuadrados, pero también pueden ajustarse de otras formas, como minimizando la "falta de ajuste" en alguna otra norma (como con la regresión de desviaciones mínimas absolutas), o minimizando una penalización. versión de la función de pérdida por mínimos cuadrados como en la regresión de crestas (penalización de $L_2$ -norm) y lazo (penalización de $L_1$ -norm). Por el contrario, el enfoque de mínimos cuadrados se puede utilizar para ajustar modelos que no son modelos lineales. Por lo tanto, aunque los términos "mínimos cuadrados" y "modelo lineal" están estrechamente relacionados, no son sinónimos.

### Importando paquetes y el conjunto de datos
"""

# Commented out IPython magic to ensure Python compatibility.
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
# %matplotlib inline

# df = pd.read_csv("https://github.com/ulewis/Ejemplos/raw/main/Datos/USA_Housing.csv")
df = pd.read_csv("https://github.com/ulewis/Ejemplos/raw/main/Datos/healthcare_dataset.csv")

df.head()  # vemos los 5 primeros datos del dataframe

"""### Consultar información básica sobre el conjunto de datos

**El método 'info()'los tipos y números de datos**
"""

df.info(verbose=True)

"""**El método 'describe()' obtiene un resumen de estadísticas de las características del conjunto de datos**"""

df.describe()

"""**El método 'columns' obtiene los nombres de las columnas (características)**"""

df.columns

"""### Visualización básica del conjunto de datos

**Pairplots usando seaborn**
"""

df['Date of Admission'] = pd.to_datetime(df['Date of Admission'])
df['Discharge Date'] = pd.to_datetime(df['Discharge Date'])

# Crear variable importante: duración de estancia
df['Length of Stay'] = (df['Discharge Date'] - df['Date of Admission']).dt.days

sns.pairplot(df)

"""**Distribución del precio (la cantidad prevista)**"""

df['Billing Amount'].plot.hist(bins=25,figsize=(8,4))

df['Billing Amount'].plot.density()

"""**Matriz de correlación y heatmap**"""

numeric_df = df.select_dtypes(include=[np.number])
numeric_df.corr()

plt.figure(figsize=(10,7))
sns.heatmap(numeric_df.corr(),annot=True,linewidths=2)

"""### Conjuntos de características y variables

**Haga una lista de los nombres de las columnas del dataframe**
"""

l_column = list(df.columns) # Haciendo una lista de las columnas
len_feature = len(l_column) # Longitud de la lista de vectores de columna
l_column

"""**Coloque todas las características numéricas en X y el precio en y, ignore la dirección, que es una cadena para la regresión lineal**"""

# Seleccionar solo las variables que lógicamente afectarían el precio (filtrando el ruido)
features = [
    'Age',
    'Gender',
    'Length of Stay',
    'Medical Condition',
    'Admission Type',
    'Medication'
]

X = df[features].copy()
y = df['Billing Amount']

# One-Hot Encoding (con dtype=int para que statsmodels no lance error)
X = pd.get_dummies(X, drop_first=True, dtype=int)

print("Tamaño de Características:",X.shape)
print("Tamaño de Variable Objetivo:",y.shape)

X.head()

y.head()

"""### División de entrenamiento-prueba

**Importamos la función train_test_split de scikit-learn**
"""

from sklearn.model_selection import train_test_split

"""**Creamos los conjuntos de entrenamiento X y de prueba y en un comando usando una proporción de división y una semilla aleatoria**"""

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=123)

"""**Verifique el tamaño y la forma de las divisiones de entrenamiento/prueba (debe estar en la proporción según el parámetro test_size anterior)**"""

print("Tamaño del conjunto de características del entrenamiento:",X_train.shape)
print("Tamaño del conjunto de características de prueba:",X_test.shape)
print("Tamaño de la variable objetivo del entrenamiento:",y_train.shape)
print("Tamaño de la variable objetivo de prueba:",y_test.shape)

"""### Ajuste y entrenamiento del modelo

**Importamos el estimador de modelo de regresión lineal de scikit-learn e lo instanciamos**
"""

model = LinearRegression()
model.fit(X_train, y_train)
y_pred_test = model.predict(X_test)

print("=== MÉTRICAS PRINCIPALES ===")
print("R2 Score (Varianza explicada):", round(metrics.r2_score(y_test, y_pred_test), 4))
print("MAE (Error absoluto medio):", round(metrics.mean_absolute_error(y_test, y_pred_test), 2))
print("RMSE (Raíz del error cuadrático medio):", round(np.sqrt(metrics.mean_squared_error(y_test, y_pred_test)), 2))

"""**Ajustamos el modelo al propio objeto instanciado**

**Verificamos la intercepción y los coeficientes y los colocamos en un DataFrame**
"""

coef_df = pd.DataFrame({
    'Variable': X.columns,
    'Coeficiente': model.coef_
}).sort_values(by='Coeficiente', ascending=False)

print("\n=== COEFICIENTES DEL MODELO ===\n")
print(coef_df)

print("\nIntercepto del modelo:\n", model.intercept_)

"""### Cálculo de errores estándar y estadística t para los coeficientes"""

cdf = pd.DataFrame({
    'Coefficients': model.coef_
}, index=X_train.columns)

n = X_train.shape[0]
k = X_train.shape[1]
dfN = n - k

# 👇 AQUÍ estaba el error
train_pred = model.predict(X_train)

train_error = np.square(train_pred - y_train)
sum_error = np.sum(train_error)

se = np.zeros(k)

for i in range(k):
    Xi = X_train.iloc[:, i]
    r = (sum_error / dfN)
    r = r / np.sum((Xi - Xi.mean())**2)
    se[i] = np.sqrt(r)

cdf['Standard Error'] = se
cdf['t-statistic'] = cdf['Coefficients'] / cdf['Standard Error']

cdf

print("Por lo tanto, las características organizadas en orden de importancia para predecir el precio de la vivienda\n",'-'*90,sep='')
l=list(cdf.sort_values('t-statistic',ascending=False).index)
print(' > \n'.join(l))

# Resumen estadístico detallado con Statsmodels
X_train_sm = sm.add_constant(X_train)
sm_model = sm.OLS(y_train, X_train_sm).fit()
print("\n=== RESUMEN ESTADÍSTICO PARA EL PROFESOR ===")
print(sm_model.summary())

"""**Diagrama de dispersión (Scatterplot) del precio previsto y el conjunto de prueba y para ver si los datos caen en una línea recta de 45 grados**"""

fig, axes = plt.subplots(1, 3, figsize=(20, 6))

# Gráfico 1: Real vs Predicho
axes[0].scatter(y_test, y_pred_test, alpha=0.3, color='royalblue')
axes[0].plot([y_test.min(), y_test.max()], [y_test.min(), y_test.max()], color='red', lw=2)
axes[0].set_title("1. Valores Reales vs Predicciones", fontsize=14)
axes[0].set_xlabel("Costo Real Facturado ($)")
axes[0].set_ylabel("Costo Predicho por el Modelo ($)")

# Gráfico 2: Histograma de Residuos
residuos = y_test - y_pred_test
sns.histplot(residuos, kde=True, ax=axes[1], color='darkorange')
axes[1].set_title("2. Distribución de los Errores (Residuos)", fontsize=14)
axes[1].set_xlabel("Error de Predicción ($)")
axes[1].set_ylabel("Frecuencia")

# Gráfico 3: Homocedasticidad
axes[2].scatter(y_pred_test, residuos, alpha=0.3, color='seagreen')
axes[2].axhline(y=0, color='red', linestyle='--', lw=2)
axes[2].set_title("3. Homocedasticidad: Predicción vs Error", fontsize=14)
axes[2].set_xlabel("Costo Predicho ($)")
axes[2].set_ylabel("Residuo (Error en $)")

plt.tight_layout()
plt.show()

"""**Interpretación de Resultados:**

El resultado de la regresión lineal dio un R^2 = 0.004, lo cual es un resultado extremadamente bajo. Esto nos indica que las variables utilizadas tienen poca o ninguna relación con el Billing Amount. Esto también se demuestra con los coeficientes asi como el error estandar, donde los resultados son valores muy altos, que afectan en gran medida las predicciones.

Como se puede observar en el primer gráfico, la nube de color azul son los valores obtenidos de Billing Amount, mientras que la línea roja es la predicción después de realizar la regresión lineal. En ese gráfico, en casi ningún punto la linea roja logra interceptarse con la nube azul, lo que indica que no hay relación entre la predicción y los valores obtenidos. Esto nos indica que la regresión lineal no fue la adecuada y que no hay relación entre las variables.

Por otro lado, el segundo gráfico nos muestra la normalidad de los errores, aca también se puede observar que la regresión no fue efectiva, ya que el error de predicción va desde -20000 a 20000, lo que indica que la posibilidad de errar en la predicción es de 20 000, lo que es un valor extremadamente alto para un error en relación a los Billing Amounts que se tienen.

Finalmente, el último gráfico muestra la homesteosidad, donde se observa que los precios predichos solo van de 24 000 a 27 000, lo que indica que el modelo de regresión lineal solo logra predecir entre ese rango mínimo, mientras que los valores esperados deberían ir en un rango mucho más amplio.

Después de analizar los gráficos se llega a la conclusión de que la regresión lineal no sirve como modeo para intentar predecir los posibles valores del Billing amount, ya que no hay relación alguna entre las variables utilizadas y la variable del precio. Aunque se intentó filtrar las variables para solo utilizar las más adecuadas.
"""

plt.figure(figsize=(10,7))
plt.title("Billing Amount real vs. el predicho",fontsize=25)
plt.xlabel("Real Billing Amount",fontsize=18)
plt.ylabel("Predicted Billing Amount", fontsize=18)
plt.scatter(x=y_test,y=predictions)

"""**Visualizamos el histograma de los residuos, es decir, errores predichos (se espera un patrón distribuido normalmente)**"""

plt.figure(figsize=(10,7))
plt.title("Histograma de residuos para verificar la normalidad ",fontsize=25)
plt.xlabel("Residuos",fontsize=18)
plt.ylabel("Densidad del kernel", fontsize=18)
sns.distplot([y_test-predictions])

"""**Diagrama de dispersión de residuos y valores predichos (Homoscedasticidad)**

"""

plt.figure(figsize=(10,7))
plt.title("Valores residuales vs. predichos\n",fontsize=25)
plt.xlabel("Precios predichos",fontsize=18)
plt.ylabel("Residuos", fontsize=18)
plt.scatter(x=predictions,y=y_test-predictions)